version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PSWD}
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: pg_isready -h postgres -p 5432 -U ${POSTGRES_USER} || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    command: -p 5432
    restart: always
    networks:
      - pgadmin-network
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PSWD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5050/ || exit
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    networks:
      - pgadmin-network
      - default

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./configfiles/sites/development.conf:/etc/nginx/conf.d/development.conf"
      - "./configfiles/nginx-common/:/etc/nginx/nginxconfig.io/"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: service nginx status || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    ports:
      - "80:80"
    restart:
      always
    depends_on:
      - pgadmin
    networks:
      - pgadmin-network
      - default

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pgadmin-network:
    external: true
  default:
    external:
      name: ${NETWORK}
